### PR TITLE
Add jQuery 3 support to 2.1.x branch

### PR DESCRIPTION
**Pull request by larowlan**
In Drupal 8, we use the joyride plugin to power the tour module.

We're hoping to update to jQuery 3 in Drupal 8.4.0 but don't want to move away from the 2.1.x branch as we have a lot of styling that is made to support the markup/classes as well as a Yaml based API that supports the existing data attributes. We've looked at the 3.x branch and would like to avoid adding the lightweight foundation framework that the solo plugin comes with.

These minor changes will make the 2.1.x branch support jQuery 3 and are backwards compatible to jQuery 1.7.

We're hoping you'll consider them.

### CODE REVIEW

**Comment by Owlbertz** [comment]
Hi @larowlan,
thank you for this PR. While the diff looks good to me, I will pull this down and test it during the week.
Am I correct assuming that this is fully backwards compatible to jQuery 2?

**Comment by larowlan** [comment]
Hi Owlbertz, I'll check that for you and report back.

**Comment by larowlan** [comment]
@Owlbertz 

`.on ` is from 1.7 http://api.jquery.com/on/
`.is` is from 1.0 http://api.jquery.com/is/

So I think that's a yes

**Comment by wimleers** [comment]
For clarity: the Drupal.org issue is https://www.drupal.org/node/2898808

**Comment by larowlan** [comment]
@Owlbertz anything more you need from me here?

Thanks in advance

**Comment by Owlbertz** [comment]
Sorry this took so long, it looks good to me.

**Comment by larowlan** [comment]
Thanks Markus, really appreciate it.
No need to apologize, we're all busy.
Is there a chance of getting a new tag for this?

On 15 Aug 2017 4:00 am, "Marius Olbertz" <notifications@github.com> wrote:

Merged #228 <https://github.com/zurb/joyride/pull/228>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zurb/joyride/pull/228#event-1205239637>, or mute the
thread

**Pull request merged**
